### ISSUE TITLE
ConcurrentModificationException called when High Scores method is called

### ISSUE THREAD

**Issue by eshaz** [AugustanaCSC490Spring2015/CipherSquadGame#2]
When I receive a high score, this exception is thrown.  This a thread / concurrency issue.  This happens around level 3 for me because that is where the score gets high enough to be added to the high scores list.

**Comment by jonathonmeyer** [comment]
Fixed it, the for loop that I had added to verify one high score entry per session wasn't sound. I didn't receive anymore errors but this needs to be verified

**Comment by eshaz** [comment]
I think that fixed it!
